title: <p align="center">Christian Liedl</p>
logo: /assets/headshot.png
description: <p align="center">Data Scientist with a PhD in Physics</p>
  <br>
   <p align="center"><a href="https://www.linkedin.com/in/christian-liedl-2aaa03133/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a></p>
theme: jekyll-theme-minimal
