title: Christian Liedl
logo: /assets/headshot.png
description: Data Scientist with a PhD in Physics
theme: jekyll-theme-minimal
github:
  another_url: https://scholar.google.com/citations?user=b0k-Uh0AAAAJ&hl=de
