title: Dr. Christian Liedl
logo: /assets/headshot.png
description: Data Scientist with a PhD in Physics
theme: jekyll-theme-minimal
show_downloads: true
github:
  zip_url: https://github.com/cliedl/portfolio/tree/main/Projects
  another_url: https://scholar.google.com/citations?user=b0k-Uh0AAAAJ&hl=de
