title: <p align="center">Dr. Christian Liedl</p>
logo: /assets/headshot.png
description: Data Scientist with a PhD in Physics
  <br>
  <a href="https://www.linkedin.com/in/christian-liedl-2aaa03133/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a>
theme: jekyll-theme-minimal
