title: Christian Liedl
logo: /assets/headshot.png
description: Data Scientist with a PhD in Physics
  <br><br><br>
  <a href="https://www.linkedin.com/in/christian-liedl-2aaa03133/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 
  <a href="https://scholar.google.com/citations?user=b0k-Uh0AAAAJ&hl=de"> <img src="./assets/scholar.png" width="100"> </a>
theme: jekyll-theme-minimal
